applicationApiVersion: v1beta1

properties:
  name:
    type: string
    description: Give your deployement a name
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  serviceAccount:
    type: string
    title: Service Account
    description: A service account for Ember to manage other cluster components. (You can just let the cluster create one)
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: cluster-admin
  apiImage:
    type: string
    default: $REGISTRY:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: image.api.registry
            repo: image.api.repository
            tag: image.api.tag
  engineImage:
    type: string
    default: $REGISTRY/ember-engine:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: image.engine.registry
            repo: image.engine.repository
            tag: image.engine.tag
  uiImage:
    type: string
    default: $REGISTRY/ember-ui:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: image.ui.registry
            repo: image.ui.repository
            tag: image.ui.tag
  kubeutilImage:
    type: string
    default: $REGISTRY/kubeutil:$TAG
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitToRegistryRepoTag:
            registry: image.kubeutil.registry
            repo: image.kubeutil.repository
            tag: image.kubeutil.tag
  mongoUserName:
    type: string
    default: "root"
    title: MongoDB User Name
    description: User name to be used to secure the MongoDB database Ember uses to store metadata.
  mongoUserPassword:
    type: string
    default: "rootPass"
    title: MongoDB Password
    description: Password to be used to secure the MongoDB database Ember uses to store metadata.
  ifExternal:
    type: string
    default: "true"
    title: Externally Expose the Deployment
    description: Do you want to externally expose Ember? (Choose true if you don't have VPN setup)
    enum:
      - "true"
      - "false"
  reloader.serviceAccount.name:
    type: string
    title: Service Account for Reloader
    description: This is another service account for Ember to use to manage the cluster.
    x-google-marketplace:
      type: SERVICE_ACCOUNT
      serviceAccount:
        roles:
          - type: ClusterRole
            rulesType: PREDEFINED
            rulesFromRoleName: cluster-admin

required:
  - name
  - namespace
  - mongoUserName
  - mongoUserPassword
  - ifExternal

x-google-marketplace:
  clusterConstraints:
    resources:
      - replicas: 3
        requests:
          cpu: 8
          memory: 32Gi
        affinity:
          simpleNodeAffinity:
            type: REQUIRE_MINIMUM_NODE_COUNT
            minimumNodeCount: 3
