dependencies:
  - name: elastic-stack
    version: 1.8.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: reloader
    repository: https://stakater.github.io/stakater-charts
    version: v0.0.49